### ISSUE TITLE
You need to run your application with root privileges

### ISSUE THREAD

**Issue by KillerX** [calum/calum.github.io#1]
This is a misleading statement:

1. Handling encryption at the app leve does not exclude a tcp proxy like Nginx itself: https://www.nginx.com/resources/admin-guide/tcp-load-balancing/ thus not requiring the application handling SSL to be on a privileged port or exposed to non-localhost at all.
2. Binding to port 80 or 443 requires an application to *start* with elevated privileges but nothing prevents the application from dropping them as soon as the port is bound thus not operating as root. As well as nice tools that help you to never need root privileges in the 1st place.

**Comment by calum** [comment]
Thank you for raising this. I agree with both of the points you make. 

For your first point, the paragraph was trying to argue that

> using a proxy to forward the traffic to your application is good practice. With a proxy already in place, changing to use HTTPS is easy. 

So, assuming someone is already using Nginx (for tcp load balancing), and that they want to upgrade to HTTPS, then it is simpler to make the changes to Nginx rather then in the application.

I do think the article needs to say something about your second point. I have never looked at tools that allow access to port 80 and 443 without root. I will edit the post to say something about this. Would you mind if I quoted you in the edit?

**Comment by KillerX** [comment]
> So, assuming someone is already using Nginx (for tcp load balancing), and that they want to upgrade to HTTPS, then it is simpler to make the changes to Nginx rather then in the application.

Actually I tried finding another one that I used before but couldn't yesterday. Found it now: http://www.haproxy.org/
But yea, I agree it makes sense.

Feel free to quote me.
